spring:
  liquibase:
    change-log: classpath:db.changelog-master.xml
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      connection:
        characterEncoding=utf-8
        CharSet=utf-8
        useUnicode=true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
